### PR TITLE
feat: Add UI for LogIn

### PR DESCRIPTION
**Pull request by prajneya**

### CODE REVIEW

**Comment by prajneya** [comment]
Added a responsive UI for the SignUp page.

**Comment by SRDewan** [comment]
Looks good to me.

**Review by PanwarJayant — APPROVED** [review]

**Comment by PanwarJayant** [comment]
Brilliant work @prajneya Keep it up!

**Review by Dayitva — APPROVED** [review]
Looks good to me!

**Review by Debayan-Saha — APPROVED** [review]
Great work

**Review by Dayitva — APPROVED** [review]

**Review by SRDewan — APPROVED** [review]

**Pull request merged**
