### PR TITLE
feat: Integrated recommender system with graphQL. Created and used se…

### PR DESCRIPTION
**Pull request by SRDewan**
…perate schema/collection for user profile details. Also fixed minor bugs in recommender algorithm.

### CODE REVIEW

**Review by prajneya — APPROVED** [review]
LGTM.

**Comment by prajneya** [comment]
@SRDewan You have tested this on the GraphQL playground, right?

**Review by Dayitva — APPROVED** [review]
Seems fine.

**Comment by SRDewan** [comment]
@prajneya yep. Right now though it will give an error until some data entry is done. Later on will handle "cold start" problem, i.e., error handling for when minimal data in database.

**Review by Debayan-Saha — APPROVED** [review]

**Pull request merged**
